### ISSUE TITLE
"UnProne" not replicating Client to Client

### ISSUE THREAD

**Issue by Vucee** [Vaei/PredictedMovement#4] opened 2023-12-28 00:51 UTC
When unproning, the replication for the capsule collision works correctly from a Listenserver pov.
However Client->Client doesn't work. The capsule half height stays at the proned height, when unproning.

The example project was used. No changes were made.

<img width="1920" alt="image" src="https://github.com/Vaei/PredictedMovement/assets/96355029/42b05496-399c-42dd-bb4e-5e386fe36088">

**Comment by Vaei** [comment] 2024-01-14 20:19
Thanks for your report. [This has been fixed now in version 1.0.4.0](https://github.com/Vaei/PredictedMovement/commit/c7da3167583089cea02e4a90a2a2bd03213bdf1b). The issue was caused by sim proxies incorrectly factoring prone locking due to a missing role check.

**Closed as completed by Vaei** 2024-01-14 20:19 UTC
